# Generated by Django 4.0.1 on 2022-03-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webdev', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='category',
            field=models.CharField(choices=[('BOOK', 'Book'), ('CODE', 'Code'), ('CRS', 'Course'), ('DOC', 'Document'), ('QUIZ', 'Quiz'), ('VID', 'Video')], max_length=4),
        ),
    ]
